# Generated by Django 4.2.2 on 2025-01-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Картинка"
            ),
        ),
    ]
