# Generated by Django 4.2.2 on 2025-01-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_entry_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="view_counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Cчётчик просмотров"
            ),
        ),
    ]
